GET http://localhost:3000/user HTTP/1.1

####

GET http://localhost:3000/xx HTTP/1.1

####


POST  http://localhost:3000/user HTTP/1.1
Content-Type: application/json
Authentication: Bearer hi

{
    "username":"demir"
}
####
